pull_request_rules:
  - name: automatic merge if author is bpg-bot
    conditions:
      - author=bpg-bot
      - status-success=build
      - body~=labels:.*semver-patch
    actions:
      merge:
        method: merge
