val ScalaJSVersion =
  Option(System.getenv("SCALAJS_VERSION")).getOrElse("0.6.31")

addSbtPlugin("org.scala-js"         % "sbt-scalajs"                   % ScalaJSVersion)
addSbtPlugin("org.portable-scala"   % "sbt-scalajs-crossproject"      % "0.6.1")
addSbtPlugin("org.portable-scala"   % "sbt-scala-native-crossproject" % "0.6.1")
addSbtPlugin("com.jsuereth"         % "sbt-pgp"                       % "2.0.1")
addSbtPlugin("pl.project13.scala"   % "sbt-jmh"                       % "0.3.7")
addSbtPlugin("com.typesafe"         % "sbt-mima-plugin"               % "0.6.1")
addSbtPlugin("com.typesafe.sbt"     % "sbt-git"                       % "1.0.0")
addSbtPlugin("org.xerial.sbt"       % "sbt-sonatype"                  % "3.8.1")
addSbtPlugin("de.heikoseeberger"    % "sbt-header"                    % "5.4.0")
addSbtPlugin("org.scalameta"        % "sbt-scalafmt"                  % "2.3.0")
addSbtPlugin("com.github.tkawachi"  % "sbt-doctest"                   % "0.9.5")
addSbtPlugin("org.scoverage"        % "sbt-scoverage"                 % "1.6.1")
addSbtPlugin("com.eed3si9n"         % "sbt-unidoc"                    % "0.4.2")
addSbtPlugin("com.47deg"            % "sbt-microsites"                % "1.1.0")
addSbtPlugin("org.scalameta"        % "sbt-mdoc"                      % "2.1.1")
