name: release

on:
  push:
    tags: ["v[0-9]+*"]

jobs:
  publish_sonatype:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
        env:
          GPG_PRIVATE_KEY: \${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: \${{ secrets.GPG_PASSPHRASE }}

      - name: Publish to Sonatype (Scala.js 1.1)
        run: csbt +clean ci-release
        env:
          SCALAJS_VERSION: 1.1.0
          PGP_PASSPHRASE: \${{ secrets.GPG_PASSPHRASE }}
          PGP_SECRET: \${{ secrets.GPG_PRIVATE_KEY }}
          SONATYPE_PASSWORD: \${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: \${{ secrets.SONATYPE_USERNAME }}

  publish_microsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: adopt@1.11

      - name: Set up Ruby 2.6 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install microsite dependencies
        run: bundle install --system --gemfile=site/Gemfile

      - name: Publish Website
        run: csbt +clean site/publishMicrosite
        env:
          GITHUB_TOKEN: \${{ secrets.GH_TOKEN }}
