name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.7 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Install microsite dependencies
        run: |
          bundle install --system --gemfile=src/main/g8/site/Gemfile

      - name: Test
        run: |
          sbt test
