name: Release

on:
  push:
    tags: ["v[0-9]+*"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v2
      - uses: olafurpg/setup-gpg@v2

      - name: Set up Ruby 2.6 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install microsite dependencies
        run: |
          bundle install --system --gemfile=site/Gemfile

      - name: Publish
        run: csbt release
        env:
          PGP_PASSPHRASE: \${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: \${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: \${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: \${{ secrets.SONATYPE_USERNAME }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
