name: scala-steward
# This workflow will launch at 00:00 every Sunday
on:
  schedule:    
    - cron: '0 0 * * 0'
  repository_dispatch:
    types: [scala-steward]

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/checkout@v2
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v2
        with:
          git_commit_gpgsign: true
          git_user_signingkey: true
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE:      ${{ secrets.GPG_PASSPHRASE }}
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@v2
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          sign-commits: true
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: ${{ steps.import_gpg.outputs.name }}
